name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    env:
      COSIGN_YES: "true"

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
        with:
          fetch-depth: 1

      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: '1.20'
          check-latest: true

      - name: Install cosign
        uses: sigstore/cosign-installer@9e9de2292db7abb3f51b7f4808d98f0d347a8919 # v3.0.2

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b # v4.2.0
        with:
          install-only: true

      - name: Get TAG
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"

      - name: Run Mage
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: buildBinaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
