name: Snapshot

on:
  push:
    branches:
      - 'main'
  pull_request:

permissions: {}

jobs:
  snapshot:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.25'
          check-latest: true

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        with:
          install-only: true

      - name: Install bom
        uses: kubernetes-sigs/release-actions/setup-bom@a30d93cf2aa029e1e4c8a6c79f766aebf429fddb # v0.3.1

      - name: Run Mage
        uses: magefile/mage-action@6f50bbb8ea47d56e62dee92392788acbc8192d0b # v3.1.0
        with:
          version: latest
          args: buildBinariesSnapshot

      - name: check binary
        run: ./dist/tejolote-amd64-linux version
